engines:
  brakeman:
    enabled: true
ratings:
  paths:
  - app/**
  - "**.rb"
exclude_paths:
- app/assets/**/*
- app/locales/**/*
- app/views/**/*
- bin/**/*
- config/**/*
- db/**/*
- doc/**/*
- lib/**/*
- public/**/*
- spec/**/*
- vendor/**/*
