dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4.1
services:
  - mongodb
  - redis-server
addons:
  apt:
    packages:
      - qt5-default
      - libqt5webkit5-dev
      - xvfb
  code_climate:
    repo_token: 6dc582455b3529d44dde0bf265ef5903a05cbbeb20341f4c6825bfaa7a111493
script:
  - xvfb-run -a bundle exec rake spec:coverage
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  app: palestrascoletivas
  api_key:
    secure: Ywt596AjohWjOtt14gpnzG9kyLTp+fiOY6Z1i07PHhaiOyoIhv41u5r+yTDhJCjcDw8R+2yOzWBa8igoL+lgJDaw4nTUV+GnFVcW/noFB65LDyjIbvUXGvWdYIN1Y9SpVsm4D9l2WkSUJsyHvFVQOQ1kIJj4zEdxB6LVtnsJeic=
